services:
    postgres:
        image: postgres:latest
        container_name: moye_postgres
        restart: always
        environment:
            # 환경 변수에서 정보를 가져옵니다.
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            # 주의: 이 경로는 공식 문서에서 권장하는 경로입니다.
            - pgdata:/var/lib/postgresql/data
        networks:
            - moye-network

    mongodb:
        image: mongo:latest
        container_name: moye_mongodb
        restart: always
        environment:
            # 환경 변수에서 정보를 가져옵니다.
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        ports:
            - '${MONGO_PORT}:27017'
        volumes:
            # 공식 문서에서 권장하는 데이터 경로입니다.
            - mongodata:/data/db
        networks:
            - moye-network

volumes:
    pgdata:
    mongodata:

networks:
    moye-network:
        driver: bridge
