version: '3.9'

services:
    postgres:
        image: postgres:latest
        container_name: moye_postgres
        restart: always
        environment:
            # 환경 변수에서 정보를 가져옵니다.
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            # 주의: 이 경로는 공식 문서에서 권장하는 경로입니다.
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
